{{ if .Values.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  labels:
    app: {{ template "hyperglance.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "hyperglance.name" . }}
  {{- if gt (.Values.replicaCount | int) 1 }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- else }}
  minAvailable: 1
  {{- end }}
{{ end }}